const TOOL_REGISTRY = {
  getWallet: {
    name: 'getWallet',
    description: 'Get current user wallet balance and transactions.',
    method: 'GET',
    endpoint: '/api/growth/wallet',
    requiredParams: [],
    allowedRoles: ['CUSTOMER', 'WORKER'],
  },
  createWalletTopupOrder: {
    name: 'createWalletTopupOrder',
    description: 'Create a wallet top-up order for the authenticated user.',
    method: 'POST',
    endpoint: '/api/growth/wallet/topup/order',
    requiredParams: ['amount'],
    allowedRoles: ['CUSTOMER', 'WORKER'],
  },
  confirmWalletTopup: {
    name: 'confirmWalletTopup',
    description: 'Confirm a wallet top-up payment after Razorpay checkout.',
    method: 'POST',
    endpoint: '/api/growth/wallet/topup/confirm',
    requiredParams: ['razorpay_payment_id', 'razorpay_order_id', 'razorpay_signature'],
    allowedRoles: ['CUSTOMER', 'WORKER'],
  },
  redeemWalletBalance: {
    name: 'redeemWalletBalance',
    description: 'Redeem wallet balance for the authenticated user.',
    method: 'POST',
    endpoint: '/api/growth/wallet/redeem',
    requiredParams: ['amount'],
    allowedRoles: ['AUTHENTICATED'],
  },
  getBookings: {
    name: 'getBookings',
    description: 'Get bookings for the authenticated user.',
    method: 'GET',
    endpoint: '/api/bookings',
    requiredParams: [],
    allowedRoles: ['AUTHENTICATED'],
  },
  getNotifications: {
    name: 'getNotifications',
    description: 'Get notifications for the authenticated user.',
    method: 'GET',
    endpoint: '/api/notifications',
    requiredParams: [],
    allowedRoles: ['AUTHENTICATED'],
  },
  getChatConversations: {
    name: 'getChatConversations',
    description: 'Get chat conversations for the authenticated user.',
    method: 'GET',
    endpoint: '/api/chat/conversations',
    requiredParams: [],
    allowedRoles: ['AUTHENTICATED'],
  },
  cancelBooking: {
    name: 'cancelBooking',
    description: 'Cancel an existing booking for the authenticated user.',
    method: 'PATCH',
    endpoint: '/api/bookings/:id/cancel',
    requiredParams: ['bookingId'],
    allowedRoles: ['AUTHENTICATED'],
  },
  createBooking: {
    name: 'createBooking',
    description: 'Create a new booking for a customer or worker.',
    method: 'POST',
    endpoint: '/api/bookings',
    requiredParams: ['serviceId', 'scheduledDate', 'addressDetails'],
    allowedRoles: ['CUSTOMER', 'WORKER'],
  },
  getBookingById: {
    name: 'getBookingById',
    description: 'Get booking details by booking ID for the authenticated user.',
    method: 'GET',
    endpoint: '/api/bookings/:id',
    requiredParams: ['bookingId'],
    allowedRoles: ['AUTHENTICATED'],
  },
  payBooking: {
    name: 'payBooking',
    description: 'Pay for a booking as customer or worker.',
    method: 'POST',
    endpoint: '/api/bookings/:id/pay',
    requiredParams: ['bookingId'],
    allowedRoles: ['CUSTOMER', 'WORKER'],
  },
  acceptBooking: {
    name: 'acceptBooking',
    description: 'Accept an open booking as worker.',
    method: 'POST',
    endpoint: '/api/bookings/:id/accept',
    requiredParams: ['bookingId'],
    allowedRoles: ['WORKER'],
  },
  startBooking: {
    name: 'startBooking',
    description: 'Start a booking as worker using OTP.',
    method: 'POST',
    endpoint: '/api/bookings/:id/start',
    requiredParams: ['bookingId', 'otp'],
    allowedRoles: ['WORKER'],
  },
  completeBooking: {
    name: 'completeBooking',
    description: 'Complete a booking as worker using OTP.',
    method: 'POST',
    endpoint: '/api/bookings/:id/complete',
    requiredParams: ['bookingId', 'otp'],
    allowedRoles: ['WORKER'],
  },
  rescheduleBooking: {
    name: 'rescheduleBooking',
    description: 'Reschedule a booking to a new date and time.',
    method: 'PATCH',
    endpoint: '/api/bookings/:id/reschedule',
    requiredParams: ['bookingId', 'newScheduledDate'],
    allowedRoles: ['AUTHENTICATED'],
  },
  getOpenBookings: {
    name: 'getOpenBookings',
    description: 'Get open bookings for worker job board.',
    method: 'GET',
    endpoint: '/api/bookings/open',
    requiredParams: [],
    allowedRoles: ['WORKER'],
  },
  createReview: {
    name: 'createReview',
    description: 'Create a review for a completed booking.',
    method: 'POST',
    endpoint: '/api/reviews',
    requiredParams: ['bookingId', 'rating'],
    allowedRoles: ['AUTHENTICATED'],
  },
  getMyWrittenReviews: {
    name: 'getMyWrittenReviews',
    description: 'List reviews written by the authenticated user.',
    method: 'GET',
    endpoint: '/api/reviews/written',
    requiredParams: [],
    allowedRoles: ['AUTHENTICATED'],
  },
  getPendingReviews: {
    name: 'getPendingReviews',
    description: 'List bookings pending a review from the authenticated user.',
    method: 'GET',
    endpoint: '/api/reviews/pending',
    requiredParams: [],
    allowedRoles: ['AUTHENTICATED'],
  },
  triggerSos: {
    name: 'triggerSos',
    description: 'Trigger SOS for an active booking.',
    method: 'POST',
    endpoint: '/api/safety/sos',
    requiredParams: ['bookingId'],
    allowedRoles: ['AUTHENTICATED'],
  },
  getEmergencyContacts: {
    name: 'getEmergencyContacts',
    description: 'Get emergency contacts for the authenticated user.',
    method: 'GET',
    endpoint: '/api/safety/contacts',
    requiredParams: [],
    allowedRoles: ['AUTHENTICATED'],
  },
  addEmergencyContact: {
    name: 'addEmergencyContact',
    description: 'Add an emergency contact for the authenticated user.',
    method: 'POST',
    endpoint: '/api/safety/contacts',
    requiredParams: ['name', 'phone', 'relation'],
    allowedRoles: ['AUTHENTICATED'],
  },
  deleteEmergencyContact: {
    name: 'deleteEmergencyContact',
    description: 'Delete an emergency contact for the authenticated user.',
    method: 'DELETE',
    endpoint: '/api/safety/contacts/:id',
    requiredParams: ['contactId'],
    allowedRoles: ['AUTHENTICATED'],
  },
  getAdminSosAlerts: {
    name: 'getAdminSosAlerts',
    description: 'Get active SOS alerts for admin monitoring.',
    method: 'GET',
    endpoint: '/api/safety/sos/alerts',
    requiredParams: [],
    allowedRoles: ['ADMIN'],
  },
  getNearbyWorkers: {
    name: 'getNearbyWorkers',
    description: 'Find nearby workers by coordinates.',
    method: 'GET',
    endpoint: '/api/location/nearby',
    requiredParams: ['lat', 'lng'],
    allowedRoles: ['AUTHENTICATED'],
  },
  validateCoupon: {
    name: 'validateCoupon',
    description: 'Validate a coupon code for a booking or service category.',
    method: 'POST',
    endpoint: '/api/growth/coupons/validate',
    requiredParams: ['code'],
    allowedRoles: ['CUSTOMER', 'WORKER'],
  },
  toggleFavorite: {
    name: 'toggleFavorite',
    description: 'Toggle a worker as a favorite.',
    method: 'POST',
    endpoint: '/api/growth/favorites/toggle',
    requiredParams: ['workerProfileId'],
    allowedRoles: ['CUSTOMER', 'WORKER'],
  },
  getFavorites: {
    name: 'getFavorites',
    description: 'List favorite workers.',
    method: 'GET',
    endpoint: '/api/growth/favorites',
    requiredParams: [],
    allowedRoles: ['CUSTOMER', 'WORKER'],
  },
  getFavoriteIds: {
    name: 'getFavoriteIds',
    description: 'List favorite worker IDs.',
    method: 'GET',
    endpoint: '/api/growth/favorites/ids',
    requiredParams: [],
    allowedRoles: ['CUSTOMER', 'WORKER'],
  },
  checkFavorite: {
    name: 'checkFavorite',
    description: 'Check whether a worker is favorited.',
    method: 'GET',
    endpoint: '/api/growth/favorites/check/:workerProfileId',
    requiredParams: ['workerProfileId'],
    allowedRoles: ['CUSTOMER', 'WORKER'],
  },
  getLoyaltySummary: {
    name: 'getLoyaltySummary',
    description: 'Get loyalty points summary.',
    method: 'GET',
    endpoint: '/api/growth/loyalty',
    requiredParams: [],
    allowedRoles: ['CUSTOMER', 'WORKER'],
  },
  redeemPoints: {
    name: 'redeemPoints',
    description: 'Redeem loyalty points.',
    method: 'POST',
    endpoint: '/api/growth/loyalty/redeem',
    requiredParams: ['points'],
    allowedRoles: ['CUSTOMER', 'WORKER'],
  },
  getWorkerServices: {
    name: 'getWorkerServices',
    description: 'Get all services offered by the authenticated worker.',
    method: 'GET',
    endpoint: '/api/workers/me/services',
    requiredParams: [],
    allowedRoles: ['WORKER'],
  },
  addWorkerService: {
    name: 'addWorkerService',
    description: 'Add a service to the authenticated worker.',
    method: 'POST',
    endpoint: '/api/workers/services',
    requiredParams: ['serviceId'],
    allowedRoles: ['WORKER'],
  },
  removeWorkerService: {
    name: 'removeWorkerService',
    description: 'Remove a service from the authenticated worker.',
    method: 'DELETE',
    endpoint: '/api/workers/services/:serviceId',
    requiredParams: ['serviceId'],
    allowedRoles: ['WORKER'],
  },
  getAdminPayments: {
    name: 'getAdminPayments',
    description: 'Get the admin payments list.',
    method: 'GET',
    endpoint: '/api/admin/payments',
    requiredParams: [],
    allowedRoles: ['ADMIN'],
  },
  createAdminService: {
    name: 'createAdminService',
    description: 'Create a new platform service as admin.',
    method: 'POST',
    endpoint: '/api/services',
    requiredParams: ['name'],
    allowedRoles: ['ADMIN'],
  },
  updateAdminService: {
    name: 'updateAdminService',
    description: 'Update a platform service as admin.',
    method: 'PATCH',
    endpoint: '/api/services/:id',
    requiredParams: ['id'],
    allowedRoles: ['ADMIN'],
  },
  deleteAdminService: {
    name: 'deleteAdminService',
    description: 'Delete a platform service as admin.',
    method: 'DELETE',
    endpoint: '/api/services/:id',
    requiredParams: ['id'],
    allowedRoles: ['ADMIN'],
  },
  markNotificationsRead: {
    name: 'markNotificationsRead',
    description: 'Mark all notifications as read for the authenticated user.',
    method: 'POST',
    endpoint: '/api/notifications/read-all',
    requiredParams: [],
    allowedRoles: ['AUTHENTICATED'],
  },
  listServices: {
    name: 'listServices',
    description: 'List services available on the platform.',
    method: 'GET',
    endpoint: '/api/services',
    requiredParams: [],
    allowedRoles: ['AUTHENTICATED'],
  },
  getServiceWorkers: {
    name: 'getServiceWorkers',
    description: 'Get workers associated with a service.',
    method: 'GET',
    endpoint: '/api/services/:serviceId/workers',
    requiredParams: ['serviceId'],
    allowedRoles: ['AUTHENTICATED'],
  },
  searchWorkers: {
    name: 'searchWorkers',
    description: 'Browse the public worker directory.',
    method: 'GET',
    endpoint: '/api/workers',
    requiredParams: [],
    allowedRoles: ['AUTHENTICATED'],
  },
  getTopWorkers: {
    name: 'getTopWorkers',
    description: 'Get top rated workers from the public leaderboard.',
    method: 'GET',
    endpoint: '/api/workers/leaderboard/top?limit=20',
    requiredParams: [],
    allowedRoles: ['AUTHENTICATED'],
  },
  getWorkerDetails: {
    name: 'getWorkerDetails',
    description: 'Get a worker public profile and services.',
    method: 'GET',
    endpoint: '/api/workers/:workerId',
    requiredParams: ['workerId'],
    allowedRoles: ['AUTHENTICATED'],
  },
  updateCustomerProfile: {
    name: 'updateCustomerProfile',
    description: 'Create or update the authenticated customer profile.',
    method: 'POST',
    endpoint: '/api/customers/profile',
    requiredParams: ['line1', 'city', 'state', 'postalCode', 'country'],
    allowedRoles: ['CUSTOMER'],
  },
  updateWorkerProfile: {
    name: 'updateWorkerProfile',
    description: 'Create or update the authenticated worker profile.',
    method: 'POST',
    endpoint: '/api/workers/profile',
    requiredParams: [],
    allowedRoles: ['WORKER'],
  },
  listAvailability: {
    name: 'listAvailability',
    description: 'List the authenticated worker availability slots.',
    method: 'GET',
    endpoint: '/api/availability/me',
    requiredParams: [],
    allowedRoles: ['WORKER'],
  },
  addAvailability: {
    name: 'addAvailability',
    description: 'Add an availability slot for the authenticated worker.',
    method: 'POST',
    endpoint: '/api/availability',
    requiredParams: ['dayOfWeek', 'startTime', 'endTime'],
    allowedRoles: ['WORKER'],
  },
  removeAvailability: {
    name: 'removeAvailability',
    description: 'Remove an availability slot for the authenticated worker.',
    method: 'DELETE',
    endpoint: '/api/availability/:id',
    requiredParams: ['id'],
    allowedRoles: ['WORKER'],
  },
  getVerificationStatus: {
    name: 'getVerificationStatus',
    description: 'Get the authenticated worker verification application status.',
    method: 'GET',
    endpoint: '/api/verification/me',
    requiredParams: [],
    allowedRoles: ['WORKER'],
  },
  applyVerification: {
    name: 'applyVerification',
    description: 'Apply for worker verification.',
    method: 'POST',
    endpoint: '/api/verification/apply',
    requiredParams: [],
    allowedRoles: ['WORKER'],
  },
  getPayoutDetails: {
    name: 'getPayoutDetails',
    description: 'Get the authenticated worker payout bank details.',
    method: 'GET',
    endpoint: '/api/payouts/bank-details',
    requiredParams: [],
    allowedRoles: ['WORKER'],
  },
  updatePayoutDetails: {
    name: 'updatePayoutDetails',
    description: 'Update the authenticated worker payout bank details.',
    method: 'POST',
    endpoint: '/api/payouts/bank-details',
    requiredParams: ['payoutMethod'],
    allowedRoles: ['WORKER'],
  },
  requestInstantPayout: {
    name: 'requestInstantPayout',
    description: 'Request an instant payout for the authenticated worker.',
    method: 'POST',
    endpoint: '/api/payouts/instant',
    requiredParams: [],
    allowedRoles: ['WORKER'],
  },
  getPayoutHistory: {
    name: 'getPayoutHistory',
    description: 'Fetch payout history for the authenticated worker.',
    method: 'GET',
    endpoint: '/api/payouts/history',
    requiredParams: [],
    allowedRoles: ['WORKER'],
  },
  getVerificationQueue: {
    name: 'getVerificationQueue',
    description: 'List verification applications for admin review.',
    method: 'GET',
    endpoint: '/api/admin/verification',
    requiredParams: [],
    allowedRoles: ['ADMIN'],
  },
  reviewVerificationApplication: {
    name: 'reviewVerificationApplication',
    description: 'Review a verification application as admin.',
    method: 'PATCH',
    endpoint: '/api/admin/verification/:id',
    requiredParams: ['id', 'status'],
    allowedRoles: ['ADMIN'],
  },
  getAdminDashboard: {
    name: 'getAdminDashboard',
    description: 'Get admin dashboard metrics and platform overview.',
    method: 'GET',
    endpoint: '/api/admin/dashboard',
    requiredParams: [],
    allowedRoles: ['ADMIN'],
  },
  getAdminAnalytics: {
    name: 'getAdminAnalytics',
    description: 'Get admin analytics summary and charts.',
    method: 'GET',
    endpoint: '/api/analytics/summary',
    requiredParams: [],
    allowedRoles: ['ADMIN'],
  },
  getAdminFraudAlerts: {
    name: 'getAdminFraudAlerts',
    description: 'Get potential fraud and quality alerts for admin monitoring.',
    method: 'GET',
    endpoint: '/api/admin/fraud-alerts',
    requiredParams: [],
    allowedRoles: ['ADMIN'],
  },
  getAdminAiAuditSummary: {
    name: 'getAdminAiAuditSummary',
    description: 'Get summary statistics for AI action audits.',
    method: 'GET',
    endpoint: '/api/admin/ai-audits/summary',
    requiredParams: [],
    allowedRoles: ['ADMIN'],
  },
  getAdminAiAudits: {
    name: 'getAdminAiAudits',
    description: 'List AI action audits for admin review.',
    method: 'GET',
    endpoint: '/api/admin/ai-audits',
    requiredParams: [],
    allowedRoles: ['ADMIN'],
  },
  getAdminUsers: {
    name: 'getAdminUsers',
    description: 'List users for admin management.',
    method: 'GET',
    endpoint: '/api/admin/users',
    requiredParams: [],
    allowedRoles: ['ADMIN'],
  },
  getAdminWorkers: {
    name: 'getAdminWorkers',
    description: 'List workers for admin management.',
    method: 'GET',
    endpoint: '/api/admin/workers',
    requiredParams: [],
    allowedRoles: ['ADMIN'],
  },
  updateAdminUserStatus: {
    name: 'updateAdminUserStatus',
    description: 'Activate or deactivate a user account as admin.',
    method: 'PATCH',
    endpoint: '/api/admin/users/:id/status',
    requiredParams: ['id', 'isActive'],
    allowedRoles: ['ADMIN'],
  },
  deleteAdminUser: {
    name: 'deleteAdminUser',
    description: 'Delete a user account as admin.',
    method: 'DELETE',
    endpoint: '/api/admin/users/:id',
    requiredParams: ['id'],
    allowedRoles: ['ADMIN'],
  },
  getAdminCoupons: {
    name: 'getAdminCoupons',
    description: 'List all coupons as admin.',
    method: 'GET',
    endpoint: '/api/admin/coupons',
    requiredParams: [],
    allowedRoles: ['ADMIN'],
  },
  createAdminCoupon: {
    name: 'createAdminCoupon',
    description: 'Create a new coupon as admin.',
    method: 'POST',
    endpoint: '/api/admin/coupons',
    requiredParams: ['code', 'discountType', 'discountValue'],
    allowedRoles: ['ADMIN'],
  },
  updateAdminCouponStatus: {
    name: 'updateAdminCouponStatus',
    description: 'Enable or disable a coupon as admin.',
    method: 'PATCH',
    endpoint: '/api/admin/coupons/:id/status',
    requiredParams: ['id', 'isActive'],
    allowedRoles: ['ADMIN'],
  },
  deleteAdminCoupon: {
    name: 'deleteAdminCoupon',
    description: 'Delete a coupon as admin.',
    method: 'DELETE',
    endpoint: '/api/admin/coupons/:id',
    requiredParams: ['id'],
    allowedRoles: ['ADMIN'],
  },
};

function getTool(toolName) {
  return TOOL_REGISTRY[toolName] || null;
}

function listTools() {
  return Object.values(TOOL_REGISTRY);
}

module.exports = {
  TOOL_REGISTRY,
  getTool,
  listTools,
};
